"""car table

Revision ID: 64b240e5bb5c
Revises: 
Create Date: 2021-04-14 10:38:05.089706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b240e5bb5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('A', sa.Integer(), nullable=True),
    sa.Column('B', sa.Integer(), nullable=True),
    sa.Column('C', sa.Integer(), nullable=True),
    sa.Column('D', sa.Integer(), nullable=True),
    sa.Column('E', sa.Integer(), nullable=True),
    sa.Column('F', sa.Integer(), nullable=True),
    sa.Column('G', sa.Integer(), nullable=True),
    sa.Column('H', sa.Integer(), nullable=True),
    sa.Column('I', sa.Integer(), nullable=True),
    sa.Column('J', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('users', sa.Column('reason', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'reason')
    op.drop_table('car')
    # ### end Alembic commands ###
