"""add aid in car

Revision ID: edd2b0f3b17d
Revises: 64b240e5bb5c
Create Date: 2021-04-14 10:48:30.166078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd2b0f3b17d'
down_revision = '64b240e5bb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('aid', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'car', ['aid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='unique')
    op.drop_column('car', 'aid')
    # ### end Alembic commands ###
